### ISSUE TITLE
Bug when running scripts/main.py

### ISSUE THREAD

**Issue by FraGard** [KTH-dESA/teaching_kit#5]
Here the error I get. Wonder if it has to do with the format of the slides or something else?

```python
$ python scripts/main.py
Traceback (most recent call last):
  File "scripts/main.py", line 17, in <module>
    pptx_extract(path,filename)
  File "C:\users\gardumi\repository\teachingkit\scripts\pptx_extract.py", line 29, in pptx_extract
    slide_text.append(slide.shapes.title.text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by lorenzo-sani** [comment]
Hi Fra, with the new version that I uploaded yesterday this issues should have been solved
